version: '3'

services:
  db:
    image: wnameless/oracle-xe-11g-r2
    environment:
      - ORACLE_SID=XE
    ports:
      - "49171:1521"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
